In [1]:
import numpy as np

In [5]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(arr2d[0])
print(arr2d[1])

[1 2 3]
[4 5 6]


In [9]:
print(arr2d[0][0])

1


In [10]:
slice1=arr2d[0:1,0:2]
print(slice1)

[[1 2]]


In [12]:
slice2=arr2d[1:,2:]
print(slice2)

[[6]
 [9]]


In [14]:
arr_len=arr2d.shape
print(arr_len)

(3, 3)
