In [1]:
import numpy as np


In [4]:
mylist1=[1,2,3]
myarray1d=np.array(mylist1)
print(myarray1d)

[1 2 3]


In [7]:
mylist2=[4,5,6]
myarray2d=np.array([mylist1,mylist2])
print(myarray2d)


[[1 2 3]
 [4 5 6]]


In [8]:
print(myarray1d.shape)

(3,)


In [9]:
print(myarray2d.shape)

(2, 3)


In [10]:
print(myarray1d.dtype)

int32


In [11]:
zero_array=np.zeros(5)
print(zero_array)


[0. 0. 0. 0. 0.]


In [14]:
zero_array2d=np.zeros([5,5])
print(zero_array2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
zero_array=np.empty(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [16]:
zero_array2d=np.empty([5,5])
print(zero_array2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
identity_array=np.eye(3)
print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
AP_Array=np.arange(0,10,2)
print(AP_Array)

[0 2 4 6 8]
