In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [3]:
arr2=arr1*arr1

In [4]:
print(arr2)

[[ 1  4  9]
 [16 25 36]]


In [5]:
arr3=arr1**3
print(arr3)

[[  1   8  27]
 [ 64 125 216]]


In [6]:
arr4=arr3-arr1
print(arr4)

[[  0   6  24]
 [ 60 120 210]]


In [7]:
arr5=1/arr1
print(arr5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
